name: Python application

on:
  push:
    branches:
      - main  # Ändern Sie dies entsprechend dem Namen Ihrer Hauptbranch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'  # Ändern Sie dies entsprechend der Python-Version, die Sie verwenden möchten

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Stellen Sie sicher, dass Ihre Anforderungen in einer Datei "requirements.txt" definiert sind

    - name: Run analysis
      run: python stock_analysis_script.py  # Hier den Befehl einfügen, um Ihr Python-Skript auszuführen

    # Weitere Schritte hier hinzufügen, je nach Ihren Anforderungen
